AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/FilePath:
  Enabled: false
