AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/slack-library-bot/helpers/daily_hours_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
