AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'ops/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/slack-library-bot/commands/hours_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
