AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
