help:
  general: |
    *Horton Bot* - Your friendly Library bot

    Commands -
    e.g. `horton service desk`

    *service desk* - Will let you knows ways to contact the ITS Service Desk
    *hours* - Will let you know today's Library hours (for all buildings)
channels:
  general: 'C04RMMCGX'
commands:
  service-desk: |
    Need to contact the ITS service desk? Here are a few options
    :slack: - Our <#C3AQL1F1A> channel!
    :email: - Email us at lib-itsd@ucsd.edu
    :slack_call: - Give us a call at 858-534-2530
