apiVersion: v1
kind: Secret
metadata:
  name: {{ template "theodor.fullname" . }}
  labels:
    app: {{ template "theodor.name" . }}
    chart: {{ template "theodor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  slack_api_token: {{ .Values.apiToken | b64enc | quote }}
