---
- name: Rollback Bot application
  hosts: lib-slackbots
  become: yes

  vars_files:
    - vars/bot.yml

  roles:
    - { role: carlosbuenosvinos.ansistrano-rollback }

  tasks:
    - name: Restarting Puma..
      systemd:
        name: puma
        state: restarted
