---
- name: Configure system for Bot application
  hosts: lib-slackbots

  vars_files:
    - vars/ansistrano.yml
    - vars/bot.yml
    - vars/rbenv.yml
    - vars/slack_token.yml

  roles:
    - { role: geerlingguy.repo-epel, become: true }
    - { role: ucsdlib.ansible-role-phantomjs, become: true }
    - { role: zzet.rbenv, become: true }

  tasks:
    - name: Install dependencies
      become: yes
      package:
        name: gcc-c++
        state: present

    - name: Install bundler gem
      gem:
        name: bundler
        state: present


- import_playbook: deploy.yml
