---
- name: Create release folders
  file:
    state: directory
    owner: "{{ bot_user }}"
    group: "{{ bot_user }}"
    mode: 0755
    path: "{{ ansistrano_release_path.stdout }}/{{ item }}"
  with_items:
    - tmp
    - sbin
    - .bundle
    - vendor
