---
- name: Bundle install Gem dependencies
  become: no
  bundler:
    state: present
    chdir: "{{ ansistrano_release_path.stdout }}"
    binstub_directory: "sbin/"
    # gemfile: "{{ ansistrano_release_path.stdout }}/Gemfile"
    deployment_mode: yes
